### ISSUE TITLE
unsetting shared_preload_libraries leads to crash

### ISSUE THREAD

**Issue by hunleyd** [ansible-collections/community.postgresql#744]
`ALTER SYSTEM SET "shared_preload_libraries" TO ''`
gives the result in the file postgresql.auto.conf
`shared_preload_libraries = '""'`
WHICH WILL LEAD TO A CRASH

_Originally posted by @Legushka in https://github.com/ansible-collections/community.postgresql/issues/78#issuecomment-2395578612_

**Comment by Andersson007** [comment]
@hunleyd thanks for creating the issue
I'm confused. I've added the `queries` return value in https://github.com/ansible-collections/community.postgresql/pull/745 (which is ready for review) where we can see in the tests I added that the module executes the following:
```
- result.queries == ["ALTER SYSTEM SET shared_preload_libraries = ''"]
```
But if i add another Restart task, the service does not start probably because of the reported behavior.
Can it be a bug of postgresql? Could you run the command manually in pgsql on your test instance and check the auto.conf file?

**Comment by Andersson007** [comment]
I've installed it and checked with pgsql:
```
postgres=# ALTER SYSTEM SET shared_preload_libraries = '';
ALTER SYSTEM
postgres=# 
\q
postgres@fedora:~$ grep -r "shared_preload_libraries" 17/data/postgresql*
17/data/postgresql.auto.conf:shared_preload_libraries = '""'
```
Looks like PG's bug.

**Comment by Andersson007** [comment]
how about https://github.com/ansible-collections/community.postgresql/pull/748 ?

**Comment by hunleyd** [comment]
this is indeed a PG bug @legushka . You should report the bug using the PG [bug form](https://www.postgresql.org/account/login/?next=/account/submitbug/)

**Comment by Andersson007** [comment]
@hunleyd @andreasscherbaum I've just submitted a C patch to pgsql-hackers@lists.postgresql.org to fix it on the postgres side.
If success, we can then allow setting shared_preload_libraries again (which we does not now, it hardcoded to fail if people try).
Fingers crossed:)
